---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: pihole
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: nitter.carvel.chart
    versionSelection:
      constraints: 0.0.1
  values:
  - secretRef:
      name: nitter-values